In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv
from numpy import matmul

from itertools import combinations

%matplotlib inline

In [34]:
paths = []
    
with open("./input-test.txt") as f:

    for idx, line in enumerate(f.read().splitlines()):
        pos, vel = line.split(" @ ")
        x, y, z = (int(v.strip()) for v in pos.split(","))
        vx, vy, vz = (int(v.strip()) for v in vel.split(","))
        
        paths.append({
            "id": idx,
            "x": x, "y": y, "z": z,
            "vx": vx, "vy": vy, "vz": vz,
        })
        
paths

[{'id': 0, 'x': 19, 'y': 13, 'z': 30, 'vx': -2, 'vy': 1, 'vz': -2},
 {'id': 1, 'x': 18, 'y': 19, 'z': 22, 'vx': -1, 'vy': -1, 'vz': -2},
 {'id': 2, 'x': 20, 'y': 25, 'z': 34, 'vx': -2, 'vy': -2, 'vz': -4},
 {'id': 3, 'x': 12, 'y': 31, 'z': 28, 'vx': -1, 'vy': -2, 'vz': -1},
 {'id': 4, 'x': 20, 'y': 19, 'z': 15, 'vx': 1, 'vy': -5, 'vz': -3}]

In [18]:
constants = []
coefs = []

for A, B in combinations(paths, 2):
    # target is x, vx, y, vy for the source point
    coef = [
        B["vy"] - A["vy"],
        A["y"]  - B["y"],
        A["vx"] - B["vx"],
        B["x"]  - A["x"],
    ]

    # don't want inf values
    if all(v != 0 for v in coef):        
        coefs.append(coef)
        constants.append((A["y"]*A["vx"]) - (A["x"]*A["vy"]) + (B["x"]*B["vy"]) - (B["y"]*B["vx"]))
        
# We want both the constants matrix and coefs matrix to be 
# the same size as the number of terms we are solving for.
# Coefs needs to be a square matrix
constants = constants[:4]
coefs = coefs[:4]

In [24]:
# use matrix inversion to solve linear equation
# AX = B
# A = coefs
# B = constants
A = np.matrix(np.array(coefs))
A

matrix([[ -2,  -6,  -1,  -1],
        [ -3, -18,  -1,  -7],
        [ -6,  -6,  -3,   1],
        [ -1,  -6,   1,   2]])

In [29]:
B = np.array(constants)
B

array([ -44,  -38, -164,    9])

In [27]:
inv(A)

matrix([[ 2.18181818, -0.45454545, -0.63636364, -0.18181818],
        [-0.5530303 ,  0.09090909,  0.14393939, -0.03030303],
        [-2.95454545,  0.63636364,  0.59090909,  0.45454545],
        [ 0.90909091, -0.27272727, -0.18181818,  0.09090909]])

In [32]:
matmul(inv(A), B)

matrix([[24., -3., 13.,  1.]])

In [39]:
constants = []
coefs = []

for A, B in combinations(paths, 2):
    # target is x, vx, z, vz for the source point
    coef = [
        B["vz"] - A["vz"],
        A["z"]  - B["z"],
        A["vx"] - B["vx"],
        B["x"]  - A["x"],
    ]

    # don't want inf values
    if all(v != 0 for v in coef):        
        coefs.append(coef)
        constants.append((A["z"]*A["vx"]) - (A["x"]*A["vz"]) + (B["x"]*B["vz"]) - (B["z"]*B["vx"]))
        
# We want both the constants matrix and coefs matrix to be 
# the same size as the number of terms we are solving for.
# Coefs needs to be a square matrix
constants = constants[:4]
coefs = coefs[:4]

A = np.matrix(np.array(coefs))
B = np.array(constants)

out = matmul(inv(A), B)
out

matrix([[24., -3., 10.,  2.]])

In [46]:
# 24, 13, 10 @ -3, 1, 2
24 + 13 + 10

47